apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: flowise
  name: flowise
  namespace: cora-ai-chatbot
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: flowise
status:
  loadBalancer: {}
